In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.decomposition import PCA
from sklearn.naive_bayes import GaussianNB
import pandas_profiling as pp
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from xgboost import XGBClassifier

In [2]:
dataset=pd.read_csv("D:/dataset.csv", encoding_errors= 'replace')
report=pp.ProfileReport(dataset)
report.to_file(output_file='output.html')


In [3]:
dataset=dataset.drop('loan_id',axis=1)


In [4]:
dataset

gender married dependents     education self_employed  applicantincome  \
0      male      no          0      graduate            no             5849   
1      male     yes          1      graduate            no             4583   
2      male     yes          0      graduate           yes             3000   
3      male     yes          0  not graduate            no             2583   
4      male      no          0      graduate            no             6000   
..      ...     ...        ...           ...           ...              ...   
609  female      no          0      graduate            no             2900   
610    male     yes         3+      graduate            no             4106   
611    male     yes          1      graduate            no             8072   
612    male     yes          2      graduate            no             7583   
613  female      no          0      graduate           yes             4583   

     coapplicantincome  loanamount  loan_amount_term  credit_history  \
0                  0.0         NaN             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

    property_area loan_status  
0           urban           y  
1           rural           n  
2           urban           y  
3           urban           y  
4           urban           y  
..            ...         ...  
609         rural           y  
610         rural           y  
611         urban           y  
612         urban           y  
613     semiurban           n  

[614 rows x 12 columns]

In [5]:
dataset

gender married dependents     education self_employed  applicantincome  \
0      male      no          0      graduate            no             5849   
1      male     yes          1      graduate            no             4583   
2      male     yes          0      graduate           yes             3000   
3      male     yes          0  not graduate            no             2583   
4      male      no          0      graduate            no             6000   
..      ...     ...        ...           ...           ...              ...   
609  female      no          0      graduate            no             2900   
610    male     yes         3+      graduate            no             4106   
611    male     yes          1      graduate            no             8072   
612    male     yes          2      graduate            no             7583   
613  female      no          0      graduate           yes             4583   

     coapplicantincome  loanamount  loan_amount_term  credit_history  \
0                  0.0         NaN             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

    property_area loan_status  
0           urban           y  
1           rural           n  
2           urban           y  
3           urban           y  
4           urban           y  
..            ...         ...  
609         rural           y  
610         rural           y  
611         urban           y  
612         urban           y  
613     semiurban           n  

[614 rows x 12 columns]

In [6]:
#bulk dataset 
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values


In [7]:
#taking care of missing numeric data.
imputer=SimpleImputer(missing_values=np.nan , strategy='most_frequent')
imputer.fit(x[: , :])
x[: , :]=imputer.transform(x[: , :])
print(x)


[['male' 'no' '0' ... 360.0 1.0 'urban']
 ['male' 'yes' '1' ... 360.0 1.0 'rural']
 ['male' 'yes' '0' ... 360.0 1.0 'urban']
 ...
 ['male' 'yes' '1' ... 360.0 1.0 'urban']
 ['male' 'yes' '2' ... 360.0 1.0 'urban']
 ['female' 'no' '0' ... 360.0 0.0 'semiurban']]


In [8]:
#one hot encoding (encoding categorical data column name sex[1])
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,2,3,4,10])], remainder='passthrough')
x = ct.fit_transform(x)
print(x) 

[[0.0 1.0 1.0 ... 120.0 360.0 1.0]
 [0.0 1.0 0.0 ... 128.0 360.0 1.0]
 [0.0 1.0 0.0 ... 66.0 360.0 1.0]
 ...
 [0.0 1.0 0.0 ... 253.0 360.0 1.0]
 [0.0 1.0 0.0 ... 187.0 360.0 1.0]
 [1.0 0.0 1.0 ... 133.0 360.0 0.0]]


In [9]:
#spliting dataset into training set and test set 
x_train, x_test, y_train,y_test=train_test_split(x, y, test_size=0.2, random_state=1)

In [10]:
#implementing logistic regression
LRclassifier = LogisticRegression(max_iter=1000, random_state=1, solver='liblinear', penalty='l1')
LRclassifier.fit(x_train, y_train)
y_pred = LRclassifier.predict(x_test)
#accuracy calculation
print("\n")
print(LRclassifier.score(x_test,y_test)*100," :- is the accuracy for logistic regression test set particularly")
#claasification_report 
print(classification_report(y_test,y_pred))



80.48780487804879  :- is the accuracy for logistic regression test set particularly
              precision    recall  f1-score   support

           n       0.94      0.41      0.57        39
           y       0.78      0.99      0.87        84

    accuracy                           0.80       123
   macro avg       0.86      0.70      0.72       123
weighted avg       0.83      0.80      0.78       123



In [11]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[16 23]
 [ 1 83]]


In [12]:
#implementing k nearest neighbors
KNNClassifier = KNeighborsClassifier(n_neighbors=3)
KNNClassifier.fit(x_train, y_train)
y_pred = KNNClassifier.predict(x_test)
#accuracy
print("\n")
print(KNNClassifier.score(x_test,y_test)*100," :- is the accuracy for knearest neighbors test set particularly")   
#claasification_report 
print(classification_report(y_test,y_pred))



59.34959349593496  :- is the accuracy for knearest neighbors test set particularly
              precision    recall  f1-score   support

           n       0.30      0.21      0.24        39
           y       0.68      0.77      0.72        84

    accuracy                           0.59       123
   macro avg       0.49      0.49      0.48       123
weighted avg       0.56      0.59      0.57       123



In [13]:
#confusion metrics 
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[ 8 31]
 [19 65]]


In [14]:
#implementing random forest classifier 
rfc = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=1)
rfc.fit(x_train,y_train)
y_pred=rfc.predict(x_test)
#accuracy
print("\n")
print(rfc.score(x_test,y_test)*100," :- is the accuracy for random forest classifier test set particularly  ")
#claasification_report 
print(classification_report(y_test,y_pred))



79.67479674796748  :- is the accuracy for random forest classifier test set particularly  
              precision    recall  f1-score   support

           n       0.72      0.59      0.65        39
           y       0.82      0.89      0.86        84

    accuracy                           0.80       123
   macro avg       0.77      0.74      0.75       123
weighted avg       0.79      0.80      0.79       123



In [15]:
#implementing the support vector classifier 
svc=SVC(kernel='linear', random_state=0)
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)
#accuracy
print("\n")
print(svc.score(x_test,y_test)*100," :- is the accuracy for support vector classifier test set particularly  ")
#claasification_report 
print(classification_report(y_test,y_pred))

In [ ]:
#implementing k nearest neighbors
KNNClassifier = KNeighborsClassifier(n_neighbors=3)
KNNClassifier.fit(x_train, y_train)
y_pred = KNNClassifier.predict(x_test)
#accuracy
print("\n")
print(KNNClassifier.score(x_test,y_test)*100," :- is the accuracy for knearest neighbors test set particularly")    
#claasification_report 
print(classification_report(y_test,y_pred))
#confusion metrics 
cm=confusion_matrix(y_test,y_pred)
print(cm)



59.34959349593496  :- is the accuracy for knearest neighbors test set particularly
              precision    recall  f1-score   support

           n       0.30      0.21      0.24        39
           y       0.68      0.77      0.72        84

    accuracy                           0.59       123
   macro avg       0.49      0.49      0.48       123
weighted avg       0.56      0.59      0.57       123

[[ 8 31]
 [19 65]]


In [ ]:
#implementing dicision tree classification 
dtr =DecisionTreeClassifier()
dtr.fit(x_train,y_train)
y_pred=dtr.predict(x_test)
#accuracy
print("\n")
print(dtr.score(x_test,y_test)*100," :- is the accuracy for dicision tree classification  test set particularly  ")
#claasification_report 
print(classification_report(y_test,y_pred))
#confusion metrics 
cm=confusion_matrix(y_test,y_pred)
print(cm)



75.60975609756098  :- is the accuracy for dicision tree classification  test set particularly  
              precision    recall  f1-score   support

           n       0.60      0.67      0.63        39
           y       0.84      0.80      0.82        84

    accuracy                           0.76       123
   macro avg       0.72      0.73      0.73       123
weighted avg       0.76      0.76      0.76       123

[[26 13]
 [17 67]]


In [ ]:
y_train

array(['n', 'n', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y',
       'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'y', 'n', 'y',
       'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n',
       'y', 'y', 'y', 'n', 'y', 'y', 'n', 'y', 'n', 'n', 'y', 'n', 'y',
       'y', 'n', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'y', 'n',
       'n', 'n', 'n', 'n', 'n', 'y', 'y', 'n', 'y', 'n', 'n', 'y', 'y',
       'y', 'n', 'y', 'y', 'y', 'y', 'n', 'y', 'y', 'n', 'y', 'n', 'y',
       'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'n', 'y', 'n', 'y',
       'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'y', 'n',
       'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'n',
       'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'n',
       'y', 'y', 'y', 'y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y',
       'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y',
       'n', 'y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'y', 'y', 'n

In [ ]:
#applying gaussiannb navi bayes classification
gnb = GaussianNB()
gnb.fit(x_train,y_train)
y_pred=gnb.predict(x_test)
#accuracy
print("\n")
print(gnb.score(x_test,y_test)*100," :- is the accuracy for gaussiannb navi bayes classification test set particularly  ")
#claasification_report 
print(classification_report(y_test,y_pred))
#confusion metrics 
cm=confusion_matrix(y_test,y_pred)
print(cm)



79.67479674796748  :- is the accuracy for gaussiannb navi bayes classification test set particularly  
              precision    recall  f1-score   support

           n       0.82      0.46      0.59        39
           y       0.79      0.95      0.86        84

    accuracy                           0.80       123
   macro avg       0.81      0.71      0.73       123
weighted avg       0.80      0.80      0.78       123

[[18 21]
 [ 4 80]]
